---
- name: Check presence of mandatory variables
  assert:
    that:
      # == sudoUser ==
      - sudoUser is defined
      - sudoUser | length > 0
      - sudoUser != None
      - sudoUser != "root"
      # == sshKeys ==
      - sshKeys is defined
      - sshKeys | length > 0
      - sshKeys != None
