---
- name: "Ensure that user {{ sudoUser }} exists, and assign it to sudoers group"
  ansible.builtin.user:
    name: "{{ sudoUser }}"
    groups:
      - sudo
    shell: /bin/bash
- name: "Add SSH keys for user {{ sudoUser }}"
  ansible.posix.authorized_key:
    user: "{{ sudoUser }}"
    key: "{{ sshKeysLink }}"
  when:
    - sshKeysLink is defined
    - sshKeysLink | length > 0
    - sshKeysLink != None
- name: Lock root user password
  ansible.builtin.user:
    name: root
    password_lock: yes
- name: "Enable passwordless sudo for {{ sudoUser }}"
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    insertafter: ^%sudo
    line: "{{ sudoUser }} ALL=(ALL) NOPASSWD: ALL"
    validate: /usr/sbin/visudo -cf %s
