---
- name: "Ensure that user {{ sudoUser }} exists, and assign it to sudoers group"
  ansible.builtin.user:
    name: "{{ sudoUser }}"
    groups:
      - sudo
    shell: /bin/bash
- name: "Add SSH keys for user {{ sudoUser }}"
  ansible.posix.authorized_key:
    user: "{{ sudoUser }}"
    key: "{{ sshKeysLink }}"
  when:
    - sshKeysLink is defined
    - sshKeysLink | length > 0
    - sshKeysLink != None
