---
- name: Check presence of mandatory variables
  import_tasks: checkVariables.yml
- name: Set default locale
  include_tasks: setLocale.yml
  when: desiredLocale != ""
- name: Set system timezone
  include_tasks: setTimezone.yml
  when: desiredTimezone != ""
- name: Update and install packages
  include_tasks: updateAndInstall.yml
- name: Configure sudo user
  include_tasks: confSudoUser.yml
